### ISSUE TITLE
TypeError: 'DefaultCfg' object does not support item assignment

### ISSUE THREAD

**Issue by twangnh** [V3Det/Detectron2-V3Det#3]
Hi @myownskyW7 @V3Det the training on detic open vocabulary detection raise the following error:
`TypeError: 'DefaultCfg' object does not support item assignment`

Could you pls help

**Comment by yhcao6** [comment]
Please install timm==0.5.4 and try again

`pip install timm==0.5.4 --upgrade`

**Comment by twangnh** [comment]
thanks, it solves the problem
